AgileHub-DQ/Backend

.github/workflows/backend-prod-cd.yml
.github/workflows/backend_ci.yml
Dockerfile

CI , CD workflow 파일 작성과 제 PC에 깃헙 러너를 구성했습니다. 
40분
본인 PC로 러너를 돌릴 때 라벨을 만들고 [evo-actions] 대신 만드신 다른 라벨로 교체하면 됩니다. 
더 좋은 방법 있으면 공유 부탁드립니다.

[#4] CI/CD workflow 파일 작성

---

.github/workflows/backend-prod-cd.yml

첫번째 러너가 실패하면 두번째 러너가 실행되도록 구성했습니다.
30분

[#9] runner 2개 사용을 위한 workflow 수정

---

src/main/resources/application.yml

driver 오타 수정

---

src/main/java/dynamicquad/agilehub/global/controller/HealthController.java
src/main/java/dynamicquad/agilehub/global/exception/ExceptionAdvice.java
src/main/java/dynamicquad/agilehub/global/exception/GeneralException.java
src/main/java/dynamicquad/agilehub/global/header/CommonResponse.java
src/main/java/dynamicquad/agilehub/global/header/ReasonDto.java
src/main/java/dynamicquad/agilehub/global/header/status/BaseStatus.java
src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
src/main/java/dynamicquad/agilehub/global/header/status/ReasonDto.java
src/main/java/dynamicquad/agilehub/global/header/status/SuccessStatus.java

공통 응답 및 전역 예외 처리 구현입니다.
3시간
CommonResponse 클래스를 통해 클라이언트에서 필요한 정보를 일관되게 응답할 수 있습니다.
e.g.
```java
CommonResponse.onSuccess(TempConverter.toResponseDto(temp));
```
GeneralException과 ExceptionAdvice를 통해 Controller 계층의 전역 예외 처리를 수행할 수 있습니다.
에러 응답은 global.header.status.ErrorStatus 열거형을 통해 관리합니다.
e.g.
```java
throw new GeneralException(TEMP_ERROR);
```

[#17] 공통 응답 및 전역 예외 처리 구현

---

build.gradle
src/main/java/dynamicquad/agilehub/global/config/SwaggerConfig.java
src/main/java/dynamicquad/agilehub/global/controller/HealthController.java
src/main/resources/application.yml

[#19] Swagger 적용

---

Dockerfile

> 17 런타임 이미지로 변경했습니다. 최종 이미지 빌드시 700MB -> 319MB
> 30분 
>

[#12] dockerfile 수정

---

src/main/resources/application.yml

>
> 2분
> 자세한 내용은 이슈 #21  에서 볼 수 있습니다

[#21] api-docs path 추가

---

src/main/resources/application.yml
src/main/resources/shema.sql

> aws에서 /etc/profile 경로에 `export AWS_DB_URL=` 이렇게 적혀있음에 따라 `application.yml`을 수정했습니다.
> 1시간
>

[#27] AWS 환경변수와 같은 변수명으로 수정

---

src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java

> contentType default 값 -> 이미지 확장자에 따라 conentType을 다르게 줄 수 있도록 했습니다. 
> 20분
>

[#44] 파일확장자 contentType 수정

---

src/main/java/dynamicquad/agilehub/global/exception/ExceptionAdvice.java
src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
src/main/java/dynamicquad/agilehub/issue/domain/epic/Epic.java
src/main/java/dynamicquad/agilehub/issue/domain/image/ImageRepository.java
src/main/java/dynamicquad/agilehub/issue/domain/story/Story.java
src/main/java/dynamicquad/agilehub/issue/domain/task/Task.java
src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
src/main/java/dynamicquad/agilehub/issue/service/IssueValidator.java
src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
src/main/java/dynamicquad/agilehub/issue/service/factory/IssueFactory.java
src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
src/main/resources/application-test.yml
src/test/java/dynamicquad/agilehub/issue/domain/image/ImageRepositoryTest.java
src/test/java/dynamicquad/agilehub/issue/service/ImageServiceTest.java
src/test/java/dynamicquad/agilehub/issue/service/IssueServiceTest.java
src/test/java/dynamicquad/agilehub/issue/service/factory/EpicFactoryTest.java

> 테스트코드 간헐적으로 실패 발생한 문제는 ` url: jdbc:h2:mem:agileHub;Mode=MySQL;DB_CLOSE_DELAY=-1;` 으로 교체하고 정상적으로 되었습니다. 파일 기반 H2로 쓰면서 지연시간 때문에 동시성 문제가 간헐적으로 발생을 했습니다
> 1일
>

[#50] 이슈 삭제, 수정 API 구현

---

src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
src/main/java/dynamicquad/agilehub/issue/comment/CommentController.java
src/main/java/dynamicquad/agilehub/issue/comment/domain/Comment.java
src/main/java/dynamicquad/agilehub/issue/comment/domain/CommentRepository.java
src/main/java/dynamicquad/agilehub/issue/comment/request/CommentRequest.java
src/main/java/dynamicquad/agilehub/issue/comment/response/CommentResponse.java
src/main/java/dynamicquad/agilehub/issue/comment/service/CommentQueryService.java
src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
src/test/java/dynamicquad/agilehub/issue/comment/CommentServiceTest.java
src/test/java/dynamicquad/agilehub/issue/comment/domain/CommentRepositoryTest.java

TODO라고 달아놓은 주석들은 인증 도메인 붙여지고 수월하게 리펙토링을 진행하기 위해 주석을 달고 있습니다. 향후 적용되고 지울 예정 입니다.
5시간
>

[#52] 이슈 내 코멘트 API 구현

---

src/main/java/dynamicquad/agilehub/issue/comment/CommentController.java
src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
src/main/java/dynamicquad/agilehub/project/controller/response/ProjectResponse.java
src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
src/main/java/dynamicquad/agilehub/sprint/controller/SprintController.java
src/main/java/dynamicquad/agilehub/sprint/controller/request/SprintRequest.java
src/main/java/dynamicquad/agilehub/sprint/service/SprintQueryService.java
src/main/java/dynamicquad/agilehub/sprint/service/SprintService.java
src/main/java/dynamicquad/agilehub/sprint/service/SprintValidator.java
src/test/java/dynamicquad/agilehub/project/service/ProjectQueryServiceTest.java
src/test/java/dynamicquad/agilehub/sprint/SprintQueryServiceTest.java
src/test/java/dynamicquad/agilehub/sprint/SprintServiceTest.java
src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java

멤버로직이 필요할 것 같은 곳에 TODO 주석을 추가했습니다. 공통적인 부분이 많아보여 저번에 말이 나왔던 `ConstraintValidator`을 적용하도록 하겠습니다. 
아래 사진처럼 `Optional` 을 잘못 쓰이는 곳이 있어서 일부분 수정했습니다. 로직이 바뀐 부분은 없습니다.
(출처: https://mangkyu.tistory.com/203)
2시간
바뀐 로직은 없습니다. 따라서 배포는 하지 않도록 하겠습니다

[#56] 멤버 로직이 필요한 부분 TODO 추가

---

src/main/java/dynamicquad/agilehub/issue/controller/ProjectIssuesController.java
src/main/java/dynamicquad/agilehub/issue/controller/response/SimpleIssueResponse.java
src/main/java/dynamicquad/agilehub/issue/domain/epic/EpicRepository.java
src/main/java/dynamicquad/agilehub/issue/domain/story/StoryRepository.java
src/main/java/dynamicquad/agilehub/issue/domain/task/TaskRepository.java
src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java

> 부모 이슈들 simple 조회 api를 구현
> 2시간
>

[#63] 부모 이슈들 simple 조회 api를 구현

---

src/main/java/dynamicquad/agilehub/global/config/SpringSecurityConfig.java
src/main/java/dynamicquad/agilehub/issue/comment/CommentController.java
src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
src/main/java/dynamicquad/agilehub/issue/controller/ProjectIssuesController.java
src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
src/main/java/dynamicquad/agilehub/sprint/controller/SprintController.java
src/main/resources/application.yml
src/test/java/dynamicquad/agilehub/issue/controller/IssueControllerTest.java
src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java

> /api 로 시작하는 것을 모두 제거했습니다.
> 10분
>

[#67] 서버 api 도메인을 수정한다 

---

src/main/java/dynamicquad/agilehub/global/config/SwaggerConfig.java

[#69] config 수정

---

src/main/java/dynamicquad/agilehub/global/auth/filter/OAuth2SuccessHandler.java

[#71] oauth 성공시 redirect 수정

---

src/main/java/dynamicquad/agilehub/issue/controller/ProjectIssuesController.java
src/main/java/dynamicquad/agilehub/issue/controller/response/IssueResponse.java
src/main/java/dynamicquad/agilehub/issue/controller/response/SimpleIssueResponse.java
src/main/java/dynamicquad/agilehub/issue/domain/task/TaskRepository.java
src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java

assignee 및 status 추가했습니다. 또한 테스크 간단 조회 API도 추가했습니다
> 1시간
>

[#78] 간단한 이슈를 조회 API 추가 정보 추가

---

Dockerfile
src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
src/main/java/dynamicquad/agilehub/project/controller/ProjectInviteController.java
src/main/java/dynamicquad/agilehub/project/controller/request/ProjectInviteRequestDto.java

초대 코드가 쿼리 파라미터가 아닌 바디에 들어오도록 수정했습니다.
20분
>

[#85] 초대 코드를 바디에 넣을 수 있도록 수정

---

README.md

[#92] readme 초안 작성

---

.github/workflows/backend-prod-cd.yml
src/main/java/dynamicquad/agilehub/global/auth/filter/JwtAuthFilter.java
src/main/java/dynamicquad/agilehub/global/config/SpringSecurityConfig.java
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/main/resources/file-error-appender.xml

[#96] 엑츄에이터 로그 파일 추출하도록 설정

---

src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
src/main/java/dynamicquad/agilehub/issue/domain/IssueStatus.java
src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
src/main/resources/application-local.yml

이슈 상태 바꾸는 API 입니다. 바꿀 상태를 JSON body 형태로 전달합니다
3~4시간 (RequestBody가 Swagger에도 존재해서 삽질했네요)
>

[#99] 상태 수정 API 추가

---

src/main/java/dynamicquad/agilehub/issue/domain/Task.java
src/main/java/dynamicquad/agilehub/issue/dto/IssueResponseDto.java
src/main/java/dynamicquad/agilehub/issue/dto/backlog/TaskResponseDto.java
src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
src/main/resources/shema.sql

> 프론트에서 테스크에 기간과 이미지 첨부 로직을 추가한 김에 삭제하는 대신 서버에서도 해당 부분을 저장하고 조회할 수 있도록 추가 구현했습니다.
> 30분
>

[#104] 테스크에 이미지 링크 및 기간 추가

---

src/main/java/dynamicquad/agilehub/global/auth/filter/OAuth2SuccessHandler.java

[#107] redirect URI '/'으로 변경

---

src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
src/main/java/dynamicquad/agilehub/issue/domain/Epic.java
src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
src/main/java/dynamicquad/agilehub/issue/domain/Story.java
src/main/java/dynamicquad/agilehub/issue/domain/Task.java
src/main/java/dynamicquad/agilehub/issue/dto/IssueRequestDto.java
src/main/java/dynamicquad/agilehub/issue/service/command/IssueService.java
src/main/resources/templates/invite.html

이슈 기간 수정 API와 이메일 초대 메세지 UI 변경했습니다
2시간

[#103] 이슈 기간 수정 API 구현

---

src/main/java/dynamicquad/agilehub/project/controller/ProjectInviteController.java
src/main/java/dynamicquad/agilehub/project/service/ProjectInviteService.java

이메일 수신 api가 프로젝트의 정보를 반환하도록 수정했습니다.
10분
>

[#120] 이메일 초대 수신 api가 프로젝트 정보를 반환하도록 수정

---

src/main/java/dynamicquad/agilehub/global/mail/service/EmailService.java
src/main/java/dynamicquad/agilehub/global/util/DateUtil.java
src/main/java/dynamicquad/agilehub/issue/repository/EpicRepository.java
src/main/java/dynamicquad/agilehub/issue/repository/StoryRepository.java
src/main/java/dynamicquad/agilehub/issue/repository/TaskRepository.java
src/main/java/dynamicquad/agilehub/issue/service/query/IssueQueryService.java
src/main/java/dynamicquad/agilehub/issue/service/query/MonthlyReportDto.java
src/main/java/dynamicquad/agilehub/report/GptService.java
src/main/java/dynamicquad/agilehub/report/ReportController.java
src/main/java/dynamicquad/agilehub/report/ReportService.java
src/main/java/dynamicquad/agilehub/report/ReportSummaryRequestDto.java
src/main/java/dynamicquad/agilehub/report/SummaryEmailInfo.java
src/main/resources/application.yml
src/main/resources/templates/reportSummary.html
src/test/java/dynamicquad/agilehub/issue/service/query/IssueQueryServiceTest.java

당월의 프로젝트에 속한 이슈들의 내용을 조회하여 gpt에 요약하고 이메일로 보내주는 기능입니다.
> 1일
>

feat: 이슈 요약 AI 추가

---

src/main/java/dynamicquad/agilehub/global/exception/GeneralException.java
src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
src/main/java/dynamicquad/agilehub/issue/IssueUpdateLoggingAspect.java
src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
src/main/java/dynamicquad/agilehub/issue/service/command/IssueService.java
src/main/java/dynamicquad/agilehub/project/domain/Project.java
src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
src/main/resources/logback-spring.xml
src/test/java/dynamicquad/agilehub/issue/service/IssueUpdateConcurrencyTest.java

이슈 동시편집시 데이터 누락 문제
